export const ADD_TODO: "ADD_TODO" = "ADD_TODO";
export const DELETE_TODO: "DELETE_TODO" = "DELETE_TODO";
export const UPDATE_TODO: "UPDATE_TODO" = "UPDATE_TODO";
export const UPDATE_FILTER_STATUS: "UPDATE_FILTER_STATUS" = "UPDATE_FILTER_STATUS";
export const CLEAR_TODOS: "CLEAR_TODOS" = "CLEAR_TODOS";
